audioplay: true
character_map:
    四国めたん: 2
    ずんだもん: 3
    春日部つむぎ: 8
    雨晴はう: 10
    波音リツ: 9
    玄野武宏: 11
    白上虎太郎: 12
    青山龍星: 13
    冥鳴ひまり: 14
    九州そら: 16
    もち子さん: 20
    剣崎雌雄: 21
default_character_name: ずんだもん
token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
voicevox_url: http://127.0.0.1:50021
Developper_Mode_**DO_NOT_CHANGE_HERE**: false
